// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/blob.hpp"
#include "../components/media_type.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A timeline-synchronized stream of self-contained audio chunks.
    ///
    /// Log each chunk at the main timeline timestamp where it starts playing.
    /// Chunks do not need to be contiguous: intervals without a chunk are treated as interruptions
    /// and remain silent in the viewer.
    ///
    /// The initial implementation supports uncompressed WAV chunks.
    /// Each chunk must be independently decodable so playback can seek after a timeline jump or gap.
    /// Do not log stream chunks as static data.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioStream {
        /// A self-contained audio chunk whose start time is the current timeline timestamp.
        std::optional<ComponentBatch> chunk;

        /// The Media Type of the chunk.
        ///
        /// If omitted, the viewer will try to guess it from the chunk contents.
        std::optional<ComponentBatch> media_type;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AudioStream";

        /// `ComponentDescriptor` for the `chunk` field.
        static constexpr auto Descriptor_chunk = ComponentDescriptor(
            ArchetypeName, "AudioStream:chunk", Loggable<rerun::components::Blob>::ComponentType
        );
        /// `ComponentDescriptor` for the `media_type` field.
        static constexpr auto Descriptor_media_type = ComponentDescriptor(
            ArchetypeName, "AudioStream:media_type",
            Loggable<rerun::components::MediaType>::ComponentType
        );

      public:
        AudioStream() = default;
        AudioStream(AudioStream&& other) = default;
        AudioStream(const AudioStream& other) = default;
        AudioStream& operator=(const AudioStream& other) = default;
        AudioStream& operator=(AudioStream&& other) = default;

        explicit AudioStream(rerun::components::Blob _chunk)
            : chunk(ComponentBatch::from_loggable(std::move(_chunk), Descriptor_chunk)
                        .value_or_throw()) {}

        /// Update only some specific fields of a `AudioStream`.
        static AudioStream update_fields() {
            return AudioStream();
        }

        /// Clear all the fields of a `AudioStream`.
        static AudioStream clear_fields();

        /// A self-contained audio chunk whose start time is the current timeline timestamp.
        AudioStream with_chunk(const rerun::components::Blob& _chunk) && {
            chunk = ComponentBatch::from_loggable(_chunk, Descriptor_chunk).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `chunk` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_chunk` should
        /// be used when logging a single row's worth of data.
        AudioStream with_many_chunk(const Collection<rerun::components::Blob>& _chunk) && {
            chunk = ComponentBatch::from_loggable(_chunk, Descriptor_chunk).value_or_throw();
            return std::move(*this);
        }

        /// The Media Type of the chunk.
        ///
        /// If omitted, the viewer will try to guess it from the chunk contents.
        AudioStream with_media_type(const rerun::components::MediaType& _media_type) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `media_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_media_type` should
        /// be used when logging a single row's worth of data.
        AudioStream with_many_media_type(const Collection<rerun::components::MediaType>& _media_type
        ) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AudioStream> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::AudioStream& archetype
        );
    };
} // namespace rerun
