// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

#include "audio_stream.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioStream AudioStream::clear_fields() {
        auto archetype = AudioStream();
        archetype.chunk =
            ComponentBatch::empty<rerun::components::Blob>(Descriptor_chunk).value_or_throw();
        archetype.media_type =
            ComponentBatch::empty<rerun::components::MediaType>(Descriptor_media_type)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioStream::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(2);
        if (chunk.has_value()) {
            columns.push_back(chunk.value().partitioned(lengths_).value_or_throw());
        }
        if (media_type.has_value()) {
            columns.push_back(media_type.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioStream::columns() {
        if (chunk.has_value()) {
            return columns(std::vector<uint32_t>(chunk.value().length(), 1));
        }
        if (media_type.has_value()) {
            return columns(std::vector<uint32_t>(media_type.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioStream>::as_batches(
        const archetypes::AudioStream& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(2);

        if (archetype.chunk.has_value()) {
            cells.push_back(archetype.chunk.value());
        }
        if (archetype.media_type.has_value()) {
            cells.push_back(archetype.media_type.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
