# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

# You can extend this class by creating a "AudioStreamExt" class in "audio_stream_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["AudioStream"]


@define(str=False, repr=False, init=False)
class AudioStream(Archetype, VisualizableArchetype):
    """
    **Archetype**: A timeline-synchronized stream of self-contained audio chunks.

    Log each chunk at the main timeline timestamp where it starts playing.
    Chunks do not need to be contiguous: intervals without a chunk are treated as interruptions
    and remain silent in the viewer.

    The initial implementation supports uncompressed WAV chunks.
    Each chunk must be independently decodable so playback can seek after a timeline jump or gap.
    Do not log stream chunks as static data.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**

    Example
    -------
    ### Log an interrupted audio stream:
    ```python
    from __future__ import annotations

    import io
    import math
    import wave

    import rerun as rr


    def make_sine_wav(frequency_hz: float, duration_s: float = 1.0) -> bytes:
        sample_rate = 44_100
        wav_buffer = io.BytesIO()

        with wave.open(wav_buffer, "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)
            wav.setframerate(sample_rate)

            for sample_index in range(int(duration_s * sample_rate)):
                t = sample_index / sample_rate
                sample = 0.35 * math.sin(2.0 * math.pi * frequency_hz * t)
                wav.writeframesraw(
                    int(sample * 32767).to_bytes(2, byteorder="little", signed=True)
                )

        return wav_buffer.getvalue()


    rr.init("rerun_example_audio_stream", spawn=True)

    rr.set_time("time", duration=0.0)
    rr.log("audio/stream", rr.archetypes.AudioStream(make_sine_wav(440.0), media_type="audio/wav"))

    # The missing interval from 1s to 2s is an interruption in the stream.
    rr.set_time("time", duration=2.0)
    rr.log("audio/stream", rr.archetypes.AudioStream(make_sine_wav(660.0), media_type="audio/wav"))
    ```

    """

    NAME: ClassVar[str] = "rerun.archetypes.AudioStream"

    def __init__(self: Any, chunk: datatypes.BlobLike, *, media_type: datatypes.Utf8Like | None = None) -> None:
        """
        Create a new instance of the AudioStream archetype.

        Parameters
        ----------
        chunk:
            A self-contained audio chunk whose start time is the current timeline timestamp.
        media_type:
            The Media Type of the chunk.

            If omitted, the viewer will try to guess it from the chunk contents.

        """

        # You can define your own __init__ function as a member of AudioStreamExt in audio_stream_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(chunk=chunk, media_type=media_type)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            chunk=None,
            media_type=None,
        )

    @classmethod
    def _clear(cls) -> AudioStream:
        """Produce an empty AudioStream, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        chunk: datatypes.BlobLike | None = None,
        media_type: datatypes.Utf8Like | None = None,
    ) -> AudioStream:
        """
        Update only some specific fields of a `AudioStream`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        chunk:
            A self-contained audio chunk whose start time is the current timeline timestamp.
        media_type:
            The Media Type of the chunk.

            If omitted, the viewer will try to guess it from the chunk contents.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "chunk": chunk,
                "media_type": media_type,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AudioStream:
        """Clear all the fields of a `AudioStream`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_chunk() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioStream:chunk",
            archetype=AudioStream.NAME,
            component_type=components.BlobBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_media_type() -> ComponentDescriptor:
        return ComponentDescriptor(
            "AudioStream:media_type",
            archetype=AudioStream.NAME,
            component_type=components.MediaTypeBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        chunk: datatypes.BlobArrayLike | None = None,
        media_type: datatypes.Utf8ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        chunk:
            A self-contained audio chunk whose start time is the current timeline timestamp.
        media_type:
            The Media Type of the chunk.

            If omitted, the viewer will try to guess it from the chunk contents.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                chunk=chunk,
                media_type=media_type,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {"AudioStream:chunk": chunk, "AudioStream:media_type": media_type}
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    chunk: components.BlobBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.BlobBatch._converter,  # type: ignore[misc]
    )
    # A self-contained audio chunk whose start time is the current timeline timestamp.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    media_type: components.MediaTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.MediaTypeBatch._converter,  # type: ignore[misc]
    )
    # The Media Type of the chunk.
    #
    # If omitted, the viewer will try to guess it from the chunk contents.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("AudioStream", overrides=self.as_component_batches(), mappings=mappings)
