// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_stream.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A timeline-synchronized stream of self-contained audio chunks.
///
/// Log each chunk at the main timeline timestamp where it starts playing.
/// Chunks do not need to be contiguous: intervals without a chunk are treated as interruptions
/// and remain silent in the viewer.
///
/// The initial implementation supports uncompressed WAV chunks.
/// Each chunk must be independently decodable so playback can seek after a timeline jump or gap.
/// Do not log stream chunks as static data.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, ::re_byte_size::SizeBytes)]
pub struct AudioStream {
    /// A self-contained audio chunk whose start time is the current timeline timestamp.
    pub chunk: Option<SerializedComponentBatch>,

    /// The Media Type of the chunk.
    ///
    /// If omitted, the viewer will try to guess it from the chunk contents.
    pub media_type: Option<SerializedComponentBatch>,
}

impl AudioStream {
    /// Returns the [`ComponentDescriptor`] for [`Self::chunk`].
    ///
    /// The corresponding component is [`crate::components::Blob`].
    #[inline]
    pub fn descriptor_chunk() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.AudioStream".into()),
                component: "AudioStream:chunk".into(),
                component_type: Some("rerun.components.Blob".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::media_type`].
    ///
    /// The corresponding component is [`crate::components::MediaType`].
    #[inline]
    pub fn descriptor_media_type() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.AudioStream".into()),
                component: "AudioStream:media_type".into(),
                component_type: Some("rerun.components.MediaType".into()),
            });
        (*DESCRIPTOR).clone()
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioStream::descriptor_chunk()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioStream::descriptor_media_type()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioStream::descriptor_chunk(),
            AudioStream::descriptor_media_type(),
        ]
    });

impl AudioStream {
    /// The total number of components in the archetype: 1 required, 1 recommended, 0 optional
    pub const NUM_COMPONENTS: usize = 2usize;
}

impl ::re_types_core::Archetype for AudioStream {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        ::re_types_core::external::re_string_interner::intern_static!(
            ::re_types_core::ArchetypeName,
            "rerun.archetypes.AudioStream"
        )
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio stream"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let chunk = arrays_by_descr
            .get(&Self::descriptor_chunk())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_chunk()));
        let media_type = arrays_by_descr
            .get(&Self::descriptor_media_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_media_type())
            });
        Ok(Self { chunk, media_type })
    }
}

impl ::re_types_core::AsComponents for AudioStream {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.chunk.clone(), self.media_type.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioStream {}

impl crate::VisualizableArchetype for AudioStream {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("AudioStream").with_overrides(self)
    }
}

impl AudioStream {
    /// Create a new `AudioStream`.
    #[inline]
    pub fn new(chunk: impl Into<crate::components::Blob>) -> Self {
        Self {
            chunk: try_serialize_field(Self::descriptor_chunk(), [chunk]),
            media_type: None,
        }
    }

    /// Update only some specific fields of a `AudioStream`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioStream`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            chunk: Some(SerializedComponentBatch::new(
                crate::components::Blob::arrow_empty(),
                Self::descriptor_chunk(),
            )),
            media_type: Some(SerializedComponentBatch::new(
                crate::components::MediaType::arrow_empty(),
                Self::descriptor_media_type(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.chunk
                .map(|chunk| chunk.partitioned(_lengths.clone()))
                .transpose()?,
            self.media_type
                .map(|media_type| media_type.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_chunk = self.chunk.as_ref().map(|b| b.array.len());
        let len_media_type = self.media_type.as_ref().map(|b| b.array.len());
        let len = None.or(len_chunk).or(len_media_type).unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// A self-contained audio chunk whose start time is the current timeline timestamp.
    #[inline]
    pub fn with_chunk(mut self, chunk: impl Into<crate::components::Blob>) -> Self {
        self.chunk = try_serialize_field(Self::descriptor_chunk(), [chunk]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Blob`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_chunk`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_chunk(
        mut self,
        chunk: impl IntoIterator<Item = impl Into<crate::components::Blob>>,
    ) -> Self {
        self.chunk = try_serialize_field(Self::descriptor_chunk(), chunk);
        self
    }

    /// The Media Type of the chunk.
    ///
    /// If omitted, the viewer will try to guess it from the chunk contents.
    #[inline]
    pub fn with_media_type(mut self, media_type: impl Into<crate::components::MediaType>) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), [media_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::MediaType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_media_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_media_type(
        mut self,
        media_type: impl IntoIterator<Item = impl Into<crate::components::MediaType>>,
    ) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), media_type);
        self
    }
}
